dist: xenial

language: python

python:
  - 3.6
  - 3.7.9
  - 3.8.12
  - 3.9
  - nightly
  - pypy3
matrix:
  allow_failures:
    - python: nightly
    - python: pypy3
install:
  - pip install -q -r dev-requirements.txt --no-cache-dir --upgrade
script:
  - make check_format
  - make test
after_success: codecov
